name = base_craft
title = Base Craft
author = Jennifer
description = BaseCraft adds essential, high-quality building blocks like concrete slabs and stairs to complete your constructions with consistency and style
release = 1